name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.FRONTEND_EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.FRONTEND_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.FRONTEND_EC2_USERNAME }}@${{ secrets.FRONTEND_EC2_HOST }} << 'EOF'
            set -e
            cd ~/OBT-Web-Frontend
            git pull origin main
            npm install
            npm run build

            echo "Clearing old files..."
            sudo rm -rf /var/www/html/*

            echo "Copying new build..."
            sudo cp -r dist/* /var/www/html/

            echo "✅ Deployment complete."
          EOF

      - name: Done
        run: echo "🚀 Frontend deployed successfully!"
